### ISSUE TITLE
Basic Mining Unit L

### ISSUE THREAD

**Issue by Aviator1280** [AstronIsTaken/du-craft#6]
I set all the skills and I get a different result on the receipt respect the actual one.
The actual receipt is
Basic Hydraulics 125
Basic Fixation 216
Basic Standard Frame 1
Basic Ore Scanner 1

I also had some problem to find the skills, may be insert here the routing we find in game it would facilitate the procedure

**Comment by AstronIsTaken** [comment]
Hi, I checked recipe and it looks good to me:

"Basic Mining Unit L": {
    "input": {
      "Basic Fixation": 216,
      "Basic Hydraulics": 125,
      "Basic Ore Scanner L": 1,
      "Basic Standard Frame L": 1
    }
  }

Can you clarify what's different? Maybe attach screenshots if possible.

As for skills, yeah, I agree, some improvements are needed to better match skills. I will work on this at some point.

**Comment by Aviator1280** [comment]
Hello,
so this is the result if I select Basic Mining Unit L
[image: image.png]

I think I understood, it actually shows what I will produce to make 1 Basic
Mining Unit L which will be more than what it is needed just because the
number of parts crafted are fixed. So I can't actually see what are the
exact amounts which means if I buy parts I will buy more than I need.
What you showed in the list is visible somewhere?
Same things happens for the material needed. It shows according to the
amount someone produced and not what is exactly needed.
Thank you


Il giorno ven 3 dic 2021 alle ore 07:01 Vasily Lementar <
***@***.***> ha scritto:

**Comment by AstronIsTaken** [comment]
I see. Yeah, it shows all numbers as you would craft everything by yourself from ore to final product and uses batching. So let's say even though you might need only 50 Pure Iron tool asks for 585 Hematite (1 batch) or less, depending on skills.

I'm working on big update where I'm going to show actual recipe with and without skills but it will take a while to release it

**Comment by Aviator1280** [comment]
You did a very nice job. I can actually see that if I go in Details it
shows the final parts as in the receipt, I don't know if the previous parts
needed are also the same, I'm trying to figure it out.
I believe you may be able to bring inside DU this tool. It would be great
to have it. Not needed on a Screen just coming out on the monitor is good
so can consult easily any time. HTML is easy to insert in DU and I believe
you are using javascript?
Not sure if you tried but I made an entire Flight System for DU,
Aviator1280.


Il giorno ven 3 dic 2021 alle ore 13:00 Vasily Lementar <
***@***.***> ha scritto:

**Comment by AstronIsTaken** [comment]
I don't think programming unit can fit all this json files with recipes :) 

And to be honest I almost stopped playing DU but still do some programming just for fun, to learn new things. Even though I'm software engineer I rarely work with web.

Of course I'm aware about Aviator system! Great stuff!

**Comment by Aviator1280** [comment]
Probably the file size would be too big but there are ways around. Can make
more files required or can actually have databank that when linked to a
programming board can work like a required file. For example some system in
my script uses the serialize script someone did but if I insert in the main
script would be too much so it is in the Programming board of the system
that needs it and will pass to the main script via databank.
I also don't play much, I like more to take care of my script but lately
the changes are pushing me to play a bit more

Il Ven 3 Dic 2021, 13:12 Vasily Lementar ***@***.***> ha
scritto:

**Comment by AstronIsTaken** [comment]
True. But I don't have any plans to do that as I don't see much benefits from having it in game and only downsides: harder to support, less features, harder to use with no good in game input. But the most important is that tool in game won't provide anything extra. Imagine if you could load your character skills in game? But nope, not supported.

Feel free to message me on Discord if you want to chat. Astron#8021
